"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ActiveProTrade, TradeOwner } from "@/lib";
import { tradeService } from "@/lib/api/trades";
import { adminTradeService } from "@/lib/api/admin";
import { useTradeUpdates } from "@/lib/hooks/useTradeUpdates";
import TradeDetailsModal from "@/components/pro-trader/signalsPage/TradeDetailsModal";

type Scope = "pro" | "copy" | "admin";
type Mode = "active" | "history";

function ownerName(owner: TradeOwner | string | undefined): string {
  if (!owner || typeof owner === "string") return "—";
  return [owner.firstName, owner.lastName].filter(Boolean).join(" ") || owner.traderID || "Trader";
}

function sourceOwner(trade: ActiveProTrade): TradeOwner | string | undefined {
  return typeof trade.sourceTradeId === "object" && trade.sourceTradeId
    ? trade.sourceTradeId.userId
    : undefined;
}

function exchangeName(trade: ActiveProTrade): string {
  return typeof trade.exchangeConnectionId === "object"
    ? trade.exchangeConnectionId.label || trade.exchangeConnectionId.exchange
    : "Exchange";
}

export default function TradeListScreen({ scope, mode }: { scope: Scope; mode: Mode }) {
  const [trades, setTrades] = useState<ActiveProTrade[]>([]);
  const [selected, setSelected] = useState<ActiveProTrade | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const response = scope === "pro"
      ? await tradeService.getProTrades(1, mode)
      : scope === "copy"
        ? await tradeService.getUserTrades(mode)
        : await adminTradeService.getTrades(mode);
    setTrades(response.trades);
    return response;
  }, [mode, scope]);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    void load()
      .catch((reason) => {
        if (!cancelled) setError(reason instanceof Error ? reason.message : "Failed to load trades.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => { cancelled = true; };
  }, [load]);

  useEffect(() => {
    if (mode !== "active") return;
    const interval = window.setInterval(() => {
      void load()
        .then((response) => {
          setTrades(response.trades);
          setSelected((current) =>
            current ? response.trades.find((trade) => trade._id === current._id) ?? null : null,
          );
        })
        .catch(() => {
          // Retain the last successful quote and avoid disrupting the table.
        });
    }, 15_000);
    return () => window.clearInterval(interval);
  }, [load, mode]);

  const applyUpdate = useCallback((update: Partial<ActiveProTrade> & { _id: string }) => {
    setTrades((current) => {
      if (mode === "active" && update.status && !["pending", "filled"].includes(update.status)) {
        return current.filter((trade) => trade._id !== update._id);
      }
      return current.map((trade) => trade._id === update._id ? { ...trade, ...update } : trade);
    });
    setSelected((current) => current?._id === update._id ? { ...current, ...update } : current);
  }, [mode]);

  useTradeUpdates({
    tradeIds: trades.map((trade) => trade._id),
    onUpdate: applyUpdate,
    onReconnect: () => { void load(); },
    enabled: mode === "active",
  });

  const totals = useMemo(() => ({
    count: trades.length,
    profit: trades.reduce((sum, trade) => sum + Number(trade.realizedPnl || 0), 0),
    copies: trades.reduce((sum, trade) => sum + (trade.copyStats?.total || 0), 0),
  }), [trades]);

  const title = mode === "active" ? "Active Trades" : "Trade History";
  const description = scope === "admin"
    ? mode === "active" ? "Monitor every open pro and copied position." : "Audit completed and unsuccessful positions across the platform."
    : scope === "pro"
      ? mode === "active" ? "Review open positions and update TP or SL across every copied position." : "Review outcomes and the proportionate activity generated by each trade."
      : mode === "active" ? "Monitor the live positions you copied from pro traders." : "Review your completed copied trades and profit settlements.";

  return (
    <div className="mx-auto w-full max-w-[1500px] space-y-6 px-2 py-4 md:px-6">
      <header>
        <h1 className="text-3xl font-bold tracking-tight text-slate-100">{title}</h1>
        <p className="mt-2 max-w-3xl text-sm text-slate-400">{description}</p>
      </header>

      <div className="grid gap-4 sm:grid-cols-3">
        <div className="rounded-xl border border-white/5 bg-surface-container-low p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Trades shown</p><p className="mt-2 text-3xl font-bold">{totals.count}</p></div>
        <div className="rounded-xl border border-white/5 bg-surface-container-low p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">{mode === "active" ? "Live positions" : "Net realized P&L"}</p><p className={`mt-2 text-3xl font-bold ${mode === "history" && totals.profit < 0 ? "text-tertiary" : "text-secondary"}`}>{mode === "active" ? totals.count : `${totals.profit.toFixed(2)} USDT`}</p></div>
        <div className="rounded-xl border border-white/5 bg-surface-container-low p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">{scope === "copy" ? "Winning trades" : "Copy executions"}</p><p className="mt-2 text-3xl font-bold">{scope === "copy" ? trades.filter((trade) => trade.tradeResult === "profit").length : totals.copies}</p></div>
      </div>

      <section className="overflow-hidden rounded-xl border border-white/5 bg-surface-container-low">
        {loading ? <div className="p-12 text-center text-slate-400">Loading trades…</div>
          : error ? <div className="p-12 text-center text-tertiary">{error}</div>
          : !trades.length ? <div className="p-12 text-center text-slate-400">No {mode} trades found.</div>
          : <div className="overflow-x-auto">
              <table className="w-full min-w-[1020px] text-left">
                <thead className="bg-surface-container-high text-[10px] uppercase tracking-widest text-slate-500"><tr>
                  <th className="p-4">Pair / owner</th><th className="p-4">Origin</th><th className="p-4">Side</th><th className="p-4">Entry / exit</th>{mode === "active" && <th className="p-4">Market price</th>}<th className="p-4">TP / SL</th><th className="p-4">{mode === "active" ? "Status" : "Result / P&L"}</th>{scope !== "copy" && <th className="p-4">Copied</th>}<th className="p-4">{mode === "active" ? "Opened" : "Closed"}</th>
                </tr></thead>
                <tbody>{trades.map((trade) => (
                  <tr key={trade._id} tabIndex={0} onClick={() => setSelected(trade)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(trade); } }} className="cursor-pointer border-t border-white/5 text-sm transition-colors hover:bg-white/5 focus:bg-white/5 focus:outline-none">
                    <td className="p-4"><p className="font-bold text-slate-100">{trade.pair}</p><p className="mt-1 text-xs text-slate-500">{scope === "admin" ? ownerName(trade.userId) : trade.tradeOrigin === "copy" ? `From ${ownerName(sourceOwner(trade))}` : exchangeName(trade)}</p></td>
                    <td className="p-4"><span className="rounded bg-white/5 px-2 py-1 text-[10px] font-bold uppercase text-slate-300">{trade.tradeOrigin}</span></td>
                    <td className={`p-4 font-bold uppercase ${trade.direction === "buy" ? "text-secondary" : "text-tertiary"}`}>{trade.direction}</td>
                    <td className="p-4 font-mono text-xs">{trade.entryFillPrice || trade.entryPrice}{mode === "history" && <> <span className="text-slate-600">→</span> {trade.exitPrice || "—"}</>}</td>
                    {mode === "active" && <td className="p-4 font-mono text-xs text-slate-100">{trade.currentMarketPrice || "—"}</td>}
                    <td className="p-4 font-mono text-xs"><span className="text-secondary">{trade.tp}</span><span className="text-slate-600"> / </span><span className="text-tertiary">{trade.sl}</span></td>
                    <td className="p-4">{mode === "active" ? <span className="text-xs font-bold uppercase">{trade.status}</span> : <><p className={`text-xs font-bold uppercase ${trade.tradeResult === "profit" ? "text-secondary" : trade.tradeResult === "loss" ? "text-tertiary" : "text-slate-400"}`}>{trade.tradeResult || trade.status}</p><p className="mt-1 font-mono text-xs">{trade.realizedPnl ?? "—"} USDT</p></>}</td>
                    {scope !== "copy" && <td className="p-4"><p className="font-bold">{trade.copyStats?.total ?? 0}</p><p className="text-[10px] text-slate-500">{trade.copyStats?.active ?? 0} active</p></td>}
                    <td className="p-4 text-xs text-slate-400">{new Date((mode === "history" ? trade.closedAt : trade.createdAt) || trade.createdAt).toLocaleString()}</td>
                  </tr>
                ))}</tbody>
              </table>
            </div>}
      </section>

      <TradeDetailsModal
        trade={selected}
        onClose={() => setSelected(null)}
        canEdit={scope === "pro" && mode === "active"}
        onUpdated={(updated) => {
          setTrades((current) => current.map((trade) => trade._id === updated._id ? updated : trade));
          setSelected(updated);
        }}
      />
    </div>
  );
}
